version: '2'

services:
  peer1.block-chain.brussels:
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=ERROR
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.block-chain.brussels
      - CORE_PEER_ADDRESS=peer1.block-chain.brussels:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.block-chain.brussels:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.block-chain.brussels:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.block-chain.brussels:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=blockchain
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=blockchain
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    container_name: peer1.block-chain.brussels
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/block-chain.brussels/peers/peer1.block-chain.brussels/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/block-chain.brussels/peers/peer1.block-chain.brussels/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053